function function_exists(func_name)
{
	if( typeof func_name === 'string' )
	{
		func_name = this.window[func_name];
	}

	return( typeof func_name === 'function' );
}

jQuery(document).ready(function($) {
	if( function_exists('count_views_from_se') )
	{
		count_views_from_se('http://www.mercotte.fr');
		//count_views_from_se('http://88.191.78.200');
	}

	//jQuery('.searchform').attr('action', '/wp-offload-search.php');
	//jQuery('#commentform').attr('action', '/wp-offload-comments-post.php');

	jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;">Meilleur P&acirc;tissier : <em><a href="/2015/12/02/la-prinsesstarta-lepreuve-technique-de-la-finale-de-la-saison-4-du-meilleur-patissier/">La Prinsesst&aring;rta</a> - <a href="/2015/11/25/les-brandy-snaps-7e-epreuve-technique-et-demi-finale-du-meilleur-patissier-saison-4/">Les Brandy Snaps</a> - <a href="/2015/11/18/le-krantz-cake-6e-epreuve-technique-le-meilleur-patissier-saison-4/">Le Krantz Cake</a> - <a href="/2015/11/11/la-feuille-dautomne-5e-epreuve-technique-le-meilleur-patissier-saison-4/">La Feuille d\'Automne</a> - <a href="/2015/11/04/lananas-bourdaloue-4eme-epreuve-technique-le-meilleur-patissier-saison-4/">L\'Ananas Bourdaloue</a><br /><a href="/2015/10/28/le-riz-a-limperatrice-3eme-epreuve-technique-le-meilleur-patissier-saison-4/">Le riz &agrave; l\'imp&eacute;ratrice</a> - <a href="/2015/10/21/la-schichttorte-ou-gateau-de-crepes-seconde-epreuve-technique-du-meilleur-patissier-saison-4/">La schichttorte ou g&acirc;teau de cr&ecirc;pes</a> - <a href="/2015/10/14/le-maroc-1ere-epreuve-technique-le-meilleur-patissier-saison-4/">Le Maroc</a></em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;">Meilleur P&acirc;tissier : <em><a href="/2014/11/26/la-charlotte-royale-8eme-epreuve-du-meilleur-patissier-saison-3-la-finale/">Charlotte Royale</a> - <a href="/2014/11/19/la-religieuse-a-lancienne-7eme-epreuve-le-meilleur-patissier-saison-3/">Religieuse &agrave; l\'Ancienne</a> - <a href="http://www.mercotte.fr/2014/11/12/la-brioche-polonaise-6eme-epreuve-technique-le-meilleur-patissier-saison-3/">Brioche Polonaise</a> - <a href="/2014/11/05/le-guillaume-tell-5eme-epreuve-le-meilleur-patissier-saison-3/">Guillaume Tell</a> - <a href="/2014/10/29/le-compiegne-4-eme-epreuve-technique-le-meilleur-patissier-saison-3-et-des-news-dans-lactu-en-fin-de-billet/">Compi&egrave;gne</a> - <a href="/2014/10/22/lalcazar-troisieme-epreuve-technique-le-meilleur-patissier-saison-3/">Alcazar</a> - <a href="/2014/10/15/le-russe-deuxieme-epreuve-technique-le-meilleur-patissier-saison-3/">Russe</a> - <a href="/2014/10/08/la-sachertorte-premiere-epreuve-technique-le-meilleur-patissier-saison-3/">Sachertorte</a></em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;">Meilleur P&acirc;tissier : <em><a href="/2014/11/26/la-charlotte-royale-8eme-epreuve-du-meilleur-patissier-saison-3-la-finale/">Charlotte Royale</a> - <a href="/2014/11/19/la-religieuse-a-lancienne-7eme-epreuve-le-meilleur-patissier-saison-3/">Religieuse &agrave; l\'Ancienne</a> - <a href="http://www.mercotte.fr/2014/11/12/la-brioche-polonaise-6eme-epreuve-technique-le-meilleur-patissier-saison-3/">Brioche Polonaise</a> - <a href="/2014/11/05/le-guillaume-tell-5eme-epreuve-le-meilleur-patissier-saison-3/">Guillaume Tell</a> - <a href="/2014/10/29/le-compiegne-4-eme-epreuve-technique-le-meilleur-patissier-saison-3-et-des-news-dans-lactu-en-fin-de-billet/">Compi&egrave;gne</a> - <a href="/2014/10/22/lalcazar-troisieme-epreuve-technique-le-meilleur-patissier-saison-3/">Alcazar</a> - <a href="/2014/10/15/le-russe-deuxieme-epreuve-technique-le-meilleur-patissier-saison-3/">Russe</a> - <a href="/2014/10/08/la-sachertorte-premiere-epreuve-technique-le-meilleur-patissier-saison-3/">Sachertorte</a></em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;">Meilleur P&acirc;tissier : <em><a href="/2013/12/16/le-paris-brest-8eme-epreuve-du-meilleur-patissier-saison-2-la-finale/">Le Paris Brest</a> - <a href="/2013/12/09/lopera-7eme-epreuve-le-meilleur-patissier-saison-2/">L\'Op&eacute;ra</a> - <a href="/2013/12/02/la-brioche-tressee-6eme-epreuve-le-meilleur-patissier-saison-2/">La Brioche Tress&eacute;e</a> - <a href="/2013/11/25/le-pastis-gascon-5eme-epreuve-le-meilleur-patissier-saison-2/">Le Pastis Gascon</a> - <a href="/2013/11/18/le-fraisier-4-eme-epreuve-technique-le-meilleur-patissier-saison-2/">Le Fraisier</a> - <a href="/2013/11/11/les-bagels-troisieme-epreuve-technique-le-meilleur-patissier-saison-2/">Les Bagels</a> - <a href="/2013/11/04/le-pithiviers-deuxieme-epreuve-technique-le-meilleur-patissier-saison-2/">Le Pithiviers</a> - <a href="/2013/10/28/le-voyageur-premiere-epreuve-technique-le-meilleur-patissier-saison-2/">Le Voyageur</a></em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;"><a href="/2012/12/15/recettes-de-fetes-pour-noel-et-le-reveillon/">Recettes de f&ecirc;tes pour No&euml;l et le R&eacute;veillon</a><br />Recettes du Meilleur P&acirc;tissier : <em><a href="/2013/12/09/lopera-7eme-epreuve-le-meilleur-patissier-saison-2/">L\'Op&eacute;ra</a> - <a href="/2013/12/02/la-brioche-tressee-6eme-epreuve-le-meilleur-patissier-saison-2/">La Brioche Tress&eacute;e</a> - <a href="/2013/11/25/le-pastis-gascon-5eme-epreuve-le-meilleur-patissier-saison-2/">Le Pastis Gascon</a> - <a href="/2013/11/18/le-fraisier-4-eme-epreuve-technique-le-meilleur-patissier-saison-2/">Le Fraisier</a> - <a href="/2013/11/11/les-bagels-troisieme-epreuve-technique-le-meilleur-patissier-saison-2/">Les Bagels</a> - <a href="/2013/11/04/le-pithiviers-deuxieme-epreuve-technique-le-meilleur-patissier-saison-2/">Le Pithiviers</a> - <a href="/2013/10/28/le-voyageur-premiere-epreuve-technique-le-meilleur-patissier-saison-2/">Le Voyageur</a></em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;"><em><a href="/2013/12/09/lopera-7eme-epreuve-le-meilleur-patissier-saison-2/">Recette de L\'Op&eacute;ra</a> - <a href="/2013/12/02/la-brioche-tressee-6eme-epreuve-le-meilleur-patissier-saison-2/">Recette de la Brioche Tress&eacute;e</a> - <a href="/2013/11/25/le-pastis-gascon-5eme-epreuve-le-meilleur-patissier-saison-2/">Recette du Pastis Gascon</a> - <a href="/2013/11/18/le-fraisier-4-eme-epreuve-technique-le-meilleur-patissier-saison-2/">Recette du Fraisier</a> - <a href="/2013/11/11/les-bagels-troisieme-epreuve-technique-le-meilleur-patissier-saison-2/">Recette des Bagels</a> - <a href="/2013/11/04/le-pithiviers-deuxieme-epreuve-technique-le-meilleur-patissier-saison-2/">Recette du Pithiviers</a> - <a href="/2013/10/28/le-voyageur-premiere-epreuve-technique-le-meilleur-patissier-saison-2/">Recette du Voyageur</a></em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;"><em>En raison du fort traffic, les pages peuvent prendre 30 secondes &agrave; apparaitre; soyez patient, inutile de recharger la page.</em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;"><em><a href="/2012/11/28/tarte-conversation-recette-trucs-astuces-et-explications/">Recette de la tarte conversation</a> - <a href="/2012/12/03/charlotte-marrons-myrtilles-le-biscuit-a-la-cuillere-2eme-epreuve-technique/">Recette de la charlotte aux fruits rouges</a> - <a href="/2012/12/10/le-baba-au-rhum-m6-le-meilleur-patissier/">Recette du baba au rhum</a> - <a href="/2012/12/17/le-saint-honore-m6-le-meilleur-patissier-la-finale/">Recette du Saint Honor&eacute;</a></em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;"><em>La <a href="/2012/11/28/tarte-conversation-recette-trucs-astuces-et-explications/">recette de la tarte conversation</a> est d&eacute;sormais disponible : <a href="/2012/11/28/tarte-conversation-recette-trucs-astuces-et-explications/">cliquez-ici</a> !</em></div>');
	//jQuery('#head').append('<div style="padding: 10px 5px; border-bottom: 2px solid #ff8080; text-align: center;"><em>La tarte conversation est dans le four, elle arrive toute chaude <strong>demain</strong> matin avec la <strong>recette</strong>, les trucs et astuces... Merci de votre patience !</em></div>');
});
